import type { Metadata } from "next";
import { Quicksand, Poppins, Open_Sans } from "next/font/google";
import "./globals.css";
import { Header } from "@/components/ui/header";

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

const openSans = Open_Sans({
  variable: "--font-open-sans",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

const quicksand = Quicksand({
  variable: "--font-quicksand",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Maicon Lara - Desenvolvedor Web",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <head>
        <link
          rel="icon"
          type="image/png"
          href="/favicon-96x96.png"
          sizes="96x96"
        />
        <link rel="icon" type="image/svg+xml" href="/favicon.svg" />
        <link rel="shortcut icon" href="/favicon.ico" />
        <link
          rel="apple-touch-icon"
          sizes="180x180"
          href="/apple-touch-icon.png"
        />
        <meta name="apple-mobile-web-app-title" content="Maicon Lara" />
        <link rel="manifest" href="/site.webmanifest" />
      </head>
      <body
        className={`flex flex-col w-full min-h-[calc(100vh-72px)] items-center justify-start ${quicksand.variable} ${poppins.variable} ${openSans.variable} antialiased`}
      >
        <Header />
        {children}
      </body>
    </html>
  );
}
